_format_version: "3.0"

_info:
  defaults:
    service:
      connect_timeout: 60000
      read_timeout: 60000
      write_timeout: 60000
      retries: 5
    route:
      https_redirect_status_code: 426
      preserve_host: false
      priority: 0
      request_buffering: true
      response_buffering: true
      strip_path: true
  select_tags:
  - ${{ env "DECK_SERVICE_TAG" }}-svc